spring:
  datasource:
    url: jdbc:mysql://210.121.177.150:3306/FMMarketing?serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true
    username: gijunpark
    password: park9832
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: withusglobalsecretkeymustbelongerthan256bitsforsecurityreasonspleasedontshare
  expiration: 86400000 # 1 day in milliseconds
